import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * One-shot local dev setup that loads the checkout through the same
 * `plugins` + `options` path an installed package uses.
 *
 * This is intentionally NON-DESTRUCTIVE. It never edits your global OpenCode
 * config.
 *
 * Why a wrapper instead of pointing straight at `../src`? OpenCode dedups
 * plugins by their declared id. The published package declares
 * `opencode-notify-webhook`, and a globally installed copy is merged before
 * the project config, so a local entry with the same id would be shadowed.
 * `dev:setup` therefore generates a tiny wrapper that re-registers the same
 * setup under `opencode-notify-webhook-dev`, and disables the global copy for
 * this location with the `-opencode-notify-webhook` directive.
 *
 * Targets:
 *   - If DISCORD_WEBHOOK_URL is set (from `.opencode/dev.env` or the
 *     environment), a real Discord target is used.
 *   - Otherwise a local capture target on http://127.0.0.1:<PORT>/hook.
 *
 * The URL is read from a gitignored file, never written into tracked sources.
 * Idempotent. Undo with `npm run dev:teardown`.
 */
const PACKAGE = "opencode-notify-webhook";
const DEV_ID = "opencode-notify-webhook-dev";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const port = process.env.PORT ?? "8787";

const opencodeDir = resolve(root, ".opencode");
const devDir = resolve(opencodeDir, "dev", "notify-dev");
const jsoncPath = join(opencodeDir, "opencode.jsonc");
const wrapperPath = join(devDir, "index.ts");
const envPath = join(opencodeDir, "dev.env");

/** Minimal KEY=VALUE parser for the gitignored dev env file. */
function loadEnvFile(path) {
  const out = {};
  if (!existsSync(path)) return out;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (!match) continue;
    let value = match[2];
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[match[1]] = value;
  }
  return out;
}

const env = { ...loadEnvFile(envPath), ...process.env };
const discordUrl = env.DISCORD_WEBHOOK_URL;

const target = discordUrl
  ? { name: "discord", type: "discord", url: discordUrl }
  : { name: "capture", type: "generic", url: `http://127.0.0.1:${port}/hook` };

// 1. Dev wrapper: same setup, distinct id so the global package cannot shadow
//    it. A plugin entry must be a directory, so this is `dev/notify-dev/` with
//    an `index.ts`. Kept under `.opencode/dev/` (not `.opencode/plugins/`) so
//    it is only loaded through the explicit entry below, with its options.
mkdirSync(devDir, { recursive: true });
writeFileSync(
  wrapperPath,
  `// Generated by scripts/dev-setup.mjs — do not edit.
// Registers the local checkout under a distinct id so the globally installed
// package does not shadow it (OpenCode dedups plugins by declared id).
import { Plugin } from "@opencode/plugin";
import { setup } from "../../../src/index.ts";

export default Plugin.define({ id: ${JSON.stringify(DEV_ID)}, setup });
`,
);
console.log(`✓ dev wrapper   ${relative(root, wrapperPath)} (id: ${DEV_ID})`);

// 2. Project config: disable the global copy for this location, then load the
//    local wrapper with options. The global config file is not touched.
const devConfig = {
  $schema: "https://opencode.ai/config.json",
  plugins: [
    `-${PACKAGE}`,
    {
      package: "./dev/notify-dev",
      options: {
        enabled: true,
        scope: "location",
        events: {
          "session.created": {},
          "session.execution.started": {},
          "session.execution.succeeded": {},
          "session.execution.failed": {},
          "permission.asked": {},
          "form.created": {},
        },
        targets: [target],
      },
    },
  ],
};

writeFileSync(jsoncPath, `${JSON.stringify(devConfig, null, 2)}\n`);
console.log(
  `✓ dev config    ${relative(root, jsoncPath)} (target: ${target.name})`,
);
console.log(
  `  disables global ${PACKAGE} for this location; ~/.config/opencode/opencode.json is untouched`,
);

// 3. Remove artifacts from the deprecated `dev:link` auto-discovery flow so
//    they cannot load the plugin a second time (without options).
for (const stale of [
  resolve(opencodeDir, "plugins", "notify.ts"),
  resolve(opencodeDir, "opencode-notify-webhook.json"),
]) {
  if (existsSync(stale)) {
    rmSync(stale, { force: true });
    console.log(`• removed stale  ${relative(root, stale)}`);
  }
}

console.log("\nNext:");
if (discordUrl) {
  console.log("  • notifications go to Discord");
} else {
  console.log("  • npm run dev:capture   # terminal A, watch payloads");
  console.log(
    "    or set DISCORD_WEBHOOK_URL in .opencode/dev.env for a real target",
  );
}
console.log(`  • run OpenCode inside ${root}`);
console.log("    (edit src/, then run `opencode reload` or restart)");
console.log(
  "  • npm run dev:isolate   # end-to-end check in a throwaway config dir",
);
